# exception1.py

try:
    4 / 0
except ZeroDivisionError as e:
    print(e)